import PDFDocument from 'pdfkit';
import * as XLSX from 'xlsx';
import type { Writable } from 'stream';
import { fmtMoney as fmt } from './currency';
import type {
  TBCurrency, PLCurrency, BSCurrency, JournalRow,
} from '../controllers/glaccounting.controller';

// General-ledger report exports — PDF (presentable statements) + XLSX
// (accountant-importable tables). Reuses the same pdfkit / SheetJS stack as
// ledgerExport.ts. Reports are typically short (one row per account), so the
// PDF layouts keep simple page-break handling.

const COLOR_HEADING = '#111827';
const COLOR_MUTED = '#6B7280';
const COLOR_BORDER = '#E5E7EB';
const M = 40;
const CONTENT_W = 515;
const PAGE_BOTTOM = 800;

async function fetchLogoBuffer(url: string | null): Promise<Buffer | null> {
  if (!url) return null;
  try { const r = await fetch(url); if (!r.ok) return null; return Buffer.from(await r.arrayBuffer()); }
  catch { return null; }
}

async function header(doc: PDFKit.PDFDocument, schoolName: string, logoUrl: string | null, title: string, subtitle: string): Promise<number> {
  const logo = await fetchLogoBuffer(logoUrl);
  if (logo) { try { doc.image(logo, M, M, { fit: [54, 54] }); } catch { /* invalid */ } }
  doc.font('Helvetica-Bold').fontSize(17).fillColor(COLOR_HEADING).text(schoolName, 104, 44);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(COLOR_HEADING).text(title, 104, 66);
  doc.font('Helvetica').fontSize(10).fillColor(COLOR_MUTED).text(subtitle, 104, 83);
  doc.moveTo(M, 108).lineTo(M + CONTENT_W, 108).strokeColor(COLOR_BORDER).lineWidth(1).stroke();
  return 124;
}

function footer(doc: PDFKit.PDFDocument, schoolName: string) {
  doc.font('Helvetica').fontSize(9).fillColor(COLOR_MUTED).text(
    `Generated by ${schoolName} · ${new Date().toISOString().split('T')[0]}`,
    M, doc.page.height - 25, { width: CONTENT_W, align: 'center', lineBreak: false },
  );
}

// ── Trial Balance ───────────────────────────────────────────────────────────
export async function streamTrialBalancePdf(stream: Writable, d: { schoolName: string; logoUrl: string | null; asOf: string | null; currencies: TBCurrency[] }): Promise<void> {
  const doc = new PDFDocument({ margin: M, size: 'A4' });
  doc.pipe(stream);
  let y = await header(doc, d.schoolName, d.logoUrl, 'Trial Balance', `As of ${d.asOf ?? 'today'}`);
  const ensure = (n: number) => { if (y + n > PAGE_BOTTOM - 20) { doc.addPage(); y = M + 20; } };
  const X_CODE = M, X_NAME = M + 50, X_DEBIT = M + 300, X_CREDIT = M + 410;

  if (d.currencies.length === 0) {
    doc.font('Helvetica').fontSize(11).fillColor(COLOR_MUTED).text('Nothing posted yet.', M, y, { width: CONTENT_W, align: 'center' });
    footer(doc, d.schoolName); doc.end(); return;
  }
  for (const block of d.currencies) {
    ensure(40);
    doc.font('Helvetica-Bold').fontSize(12).fillColor(COLOR_HEADING).text(`${block.currency}${block.balanced ? '' : '  (out of balance)'}`, M, y); y += 18;
    doc.font('Helvetica-Bold').fontSize(8).fillColor(COLOR_MUTED);
    doc.text('CODE', X_CODE, y, { lineBreak: false }); doc.text('ACCOUNT', X_NAME, y, { lineBreak: false });
    doc.text('DEBIT', X_DEBIT, y, { width: 100, align: 'right', lineBreak: false }); doc.text('CREDIT', X_CREDIT, y, { width: 105, align: 'right', lineBreak: false });
    y += 12; doc.moveTo(M, y).lineTo(M + CONTENT_W, y).strokeColor(COLOR_BORDER).stroke(); y += 5;
    for (const a of block.accounts) {
      ensure(14);
      doc.font('Helvetica').fontSize(9).fillColor(COLOR_HEADING);
      doc.text(a.code, X_CODE, y, { width: 48, lineBreak: false });
      doc.text(a.name, X_NAME, y, { width: 245, ellipsis: true, lineBreak: false });
      doc.text(a.debit ? fmt(a.debit, block.currency) : '', X_DEBIT, y, { width: 100, align: 'right', lineBreak: false });
      doc.text(a.credit ? fmt(a.credit, block.currency) : '', X_CREDIT, y, { width: 105, align: 'right', lineBreak: false });
      y += 14;
    }
    ensure(18); doc.moveTo(M, y).lineTo(M + CONTENT_W, y).strokeColor(COLOR_BORDER).stroke(); y += 4;
    doc.font('Helvetica-Bold').fontSize(9).fillColor(COLOR_HEADING);
    doc.text('Totals', X_NAME, y, { lineBreak: false });
    doc.text(fmt(block.totalDebit, block.currency), X_DEBIT, y, { width: 100, align: 'right', lineBreak: false });
    doc.text(fmt(block.totalCredit, block.currency), X_CREDIT, y, { width: 105, align: 'right', lineBreak: false });
    y += 26;
  }
  footer(doc, d.schoolName); doc.end();
}

// ── Statement renderer (P&L + Balance Sheet share this section layout) ──────
interface Section { title: string; rows: { code: string; name: string; amount: number }[]; total: number; totalLabel: string }
async function streamStatementPdf(stream: Writable, d: { schoolName: string; logoUrl: string | null; title: string; subtitle: string; blocks: { currency: string; sections: Section[]; footerLabel?: string; footerAmount?: number }[] }): Promise<void> {
  const doc = new PDFDocument({ margin: M, size: 'A4' });
  doc.pipe(stream);
  let y = await header(doc, d.schoolName, d.logoUrl, d.title, d.subtitle);
  const ensure = (n: number) => { if (y + n > PAGE_BOTTOM - 20) { doc.addPage(); y = M + 20; } };
  const X_CODE = M, X_NAME = M + 50, X_AMT = M + CONTENT_W - 120;

  if (d.blocks.length === 0) {
    doc.font('Helvetica').fontSize(11).fillColor(COLOR_MUTED).text('Nothing to report yet.', M, y, { width: CONTENT_W, align: 'center' });
    footer(doc, d.schoolName); doc.end(); return;
  }
  for (const block of d.blocks) {
    ensure(30);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(COLOR_HEADING).text(block.currency, M, y); y += 20;
    for (const s of block.sections) {
      ensure(28);
      doc.font('Helvetica-Bold').fontSize(9).fillColor(COLOR_MUTED).text(s.title.toUpperCase(), M, y); y += 14;
      for (const r of s.rows) {
        ensure(14);
        doc.font('Helvetica').fontSize(9).fillColor(COLOR_HEADING);
        if (r.code) doc.text(r.code, X_CODE, y, { width: 48, lineBreak: false });
        doc.text(r.name, X_NAME, y, { width: 300, ellipsis: true, lineBreak: false });
        doc.text(fmt(r.amount, block.currency), X_AMT, y, { width: 120, align: 'right', lineBreak: false });
        y += 14;
      }
      if (s.rows.length === 0) { doc.font('Helvetica').fontSize(9).fillColor(COLOR_MUTED).text('—', X_NAME, y, { lineBreak: false }); y += 14; }
      doc.moveTo(X_NAME, y).lineTo(M + CONTENT_W, y).strokeColor(COLOR_BORDER).stroke(); y += 3;
      doc.font('Helvetica-Bold').fontSize(9).fillColor(COLOR_HEADING);
      doc.text(s.totalLabel, X_NAME, y, { lineBreak: false });
      doc.text(fmt(s.total, block.currency), X_AMT, y, { width: 120, align: 'right', lineBreak: false });
      y += 20;
    }
    if (block.footerLabel) {
      ensure(20); doc.moveTo(M, y).lineTo(M + CONTENT_W, y).strokeColor(COLOR_BORDER).lineWidth(1).stroke(); y += 5;
      doc.font('Helvetica-Bold').fontSize(11).fillColor(COLOR_HEADING).text(block.footerLabel, M, y, { lineBreak: false });
      doc.text(fmt(block.footerAmount ?? 0, block.currency), X_AMT, y, { width: 120, align: 'right', lineBreak: false });
      y += 28;
    }
  }
  footer(doc, d.schoolName); doc.end();
}

export function streamIncomeStatementPdf(stream: Writable, d: { schoolName: string; logoUrl: string | null; startDate: string | null; endDate: string | null; currencies: PLCurrency[] }): Promise<void> {
  return streamStatementPdf(stream, {
    schoolName: d.schoolName, logoUrl: d.logoUrl, title: 'Income Statement',
    subtitle: `${d.startDate ?? '...'} to ${d.endDate ?? 'today'}`,
    blocks: d.currencies.map(c => ({
      currency: c.currency,
      sections: [
        { title: 'Income', rows: c.income, total: c.totalIncome, totalLabel: 'Total income' },
        { title: 'Expenses', rows: c.expense, total: c.totalExpense, totalLabel: 'Total expenses' },
      ],
      footerLabel: c.netIncome >= 0 ? 'Net profit' : 'Net loss',
      footerAmount: c.netIncome,
    })),
  });
}

export function streamBalanceSheetPdf(stream: Writable, d: { schoolName: string; logoUrl: string | null; asOf: string | null; currencies: BSCurrency[] }): Promise<void> {
  return streamStatementPdf(stream, {
    schoolName: d.schoolName, logoUrl: d.logoUrl, title: 'Balance Sheet',
    subtitle: `As of ${d.asOf ?? 'today'}`,
    blocks: d.currencies.map(c => ({
      currency: c.currency,
      sections: [
        { title: 'Assets', rows: c.assets, total: c.totalAssets, totalLabel: 'Total assets' },
        { title: 'Liabilities', rows: c.liabilities, total: c.totalLiabilities, totalLabel: 'Total liabilities' },
        { title: 'Equity', rows: [...c.equity, { code: '', name: 'Current period earnings', amount: c.currentEarnings }], total: c.totalEquity, totalLabel: 'Total equity' },
      ],
      footerLabel: 'Liabilities + Equity',
      footerAmount: Math.round((c.totalLiabilities + c.totalEquity) * 100) / 100,
    })),
  });
}

// ── XLSX builders ────────────────────────────────────────────────────────────
function withFilter(ws: XLSX.WorkSheet, lastRow: number, lastCol: string) {
  if (lastRow > 1) ws['!autofilter'] = { ref: `A1:${lastCol}${lastRow}` };
  (ws as Record<string, unknown>)['!views'] = [{ state: 'frozen', ySplit: 1, topLeftCell: 'A2' }];
}

export function buildTrialBalanceXlsx(d: { currencies: TBCurrency[] }): Buffer {
  const wb = XLSX.utils.book_new();
  const rows: (string | number)[][] = [['Currency', 'Code', 'Account', 'Type', 'Debit', 'Credit']];
  for (const c of d.currencies) {
    for (const a of c.accounts) rows.push([c.currency, a.code, a.name, a.type, a.debit, a.credit]);
    rows.push([c.currency, '', 'TOTALS', '', c.totalDebit, c.totalCredit]);
  }
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 10 }, { wch: 8 }, { wch: 32 }, { wch: 12 }, { wch: 16 }, { wch: 16 }];
  withFilter(ws, rows.length, 'F');
  XLSX.utils.book_append_sheet(wb, ws, 'Trial Balance');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
}

export function buildIncomeStatementXlsx(d: { currencies: PLCurrency[] }): Buffer {
  const wb = XLSX.utils.book_new();
  const rows: (string | number)[][] = [['Currency', 'Section', 'Code', 'Account', 'Amount']];
  for (const c of d.currencies) {
    for (const a of c.income) rows.push([c.currency, 'Income', a.code, a.name, a.amount]);
    rows.push([c.currency, 'Income', '', 'Total income', c.totalIncome]);
    for (const a of c.expense) rows.push([c.currency, 'Expense', a.code, a.name, a.amount]);
    rows.push([c.currency, 'Expense', '', 'Total expenses', c.totalExpense]);
    rows.push([c.currency, 'Net', '', c.netIncome >= 0 ? 'Net profit' : 'Net loss', c.netIncome]);
  }
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 10 }, { wch: 10 }, { wch: 8 }, { wch: 32 }, { wch: 16 }];
  withFilter(ws, rows.length, 'E');
  XLSX.utils.book_append_sheet(wb, ws, 'Income Statement');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
}

export function buildBalanceSheetXlsx(d: { currencies: BSCurrency[] }): Buffer {
  const wb = XLSX.utils.book_new();
  const rows: (string | number)[][] = [['Currency', 'Section', 'Code', 'Account', 'Amount']];
  for (const c of d.currencies) {
    for (const a of c.assets) rows.push([c.currency, 'Asset', a.code, a.name, a.amount]);
    rows.push([c.currency, 'Asset', '', 'Total assets', c.totalAssets]);
    for (const a of c.liabilities) rows.push([c.currency, 'Liability', a.code, a.name, a.amount]);
    rows.push([c.currency, 'Liability', '', 'Total liabilities', c.totalLiabilities]);
    for (const a of c.equity) rows.push([c.currency, 'Equity', a.code, a.name, a.amount]);
    rows.push([c.currency, 'Equity', '', 'Current period earnings', c.currentEarnings]);
    rows.push([c.currency, 'Equity', '', 'Total equity', c.totalEquity]);
  }
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 10 }, { wch: 11 }, { wch: 8 }, { wch: 32 }, { wch: 16 }];
  withFilter(ws, rows.length, 'E');
  XLSX.utils.book_append_sheet(wb, ws, 'Balance Sheet');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
}

export function buildJournalXlsx(d: { entries: JournalRow[] }): Buffer {
  const wb = XLSX.utils.book_new();
  const rows: (string | number)[][] = [['Entry #', 'Date', 'Source', 'Memo', 'Code', 'Account', 'Debit', 'Credit', 'Currency', 'Description']];
  for (const e of d.entries) {
    for (const l of e.lines) {
      rows.push([e.entryNo, e.entryDate, e.isReversal ? `${e.source} (reversal)` : e.source, e.memo ?? '', l.code, l.name, l.debit || '', l.credit || '', l.currency, l.description ?? '']);
    }
  }
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 8 }, { wch: 12 }, { wch: 16 }, { wch: 22 }, { wch: 8 }, { wch: 28 }, { wch: 14 }, { wch: 14 }, { wch: 9 }, { wch: 28 }];
  withFilter(ws, rows.length, 'J');
  XLSX.utils.book_append_sheet(wb, ws, 'Journal');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
}
